
package Interface;

import Estruturas.Pilha;
import Exceptions.*;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Pablo Suria
 */
public class pnlPilha extends javax.swing.JPanel {

    private Pilha pilha;
    
    public pnlPilha(int tamanho) {
        initComponents();
        pilha = new Pilha(tamanho);
        lblTamMaximo.setText(lblTamMaximo.getText() + tamanho);
        atualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValor = new javax.swing.JLabel();
        btnPop = new javax.swing.JButton();
        txtValor = new javax.swing.JTextField();
        btnPush = new javax.swing.JButton();
        btnTop = new javax.swing.JButton();
        lblTamMaximo = new javax.swing.JLabel();
        lblTamAtual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pnlEstru = new javax.swing.JPanel();

        setBackground(new java.awt.Color(195, 195, 210));

        lblValor.setText("Valor:");

        btnPop.setBackground(new java.awt.Color(195, 195, 210));
        btnPop.setText("Pop");
        btnPop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPopActionPerformed(evt);
            }
        });

        btnPush.setBackground(new java.awt.Color(195, 195, 210));
        btnPush.setText("Push");
        btnPush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPushActionPerformed(evt);
            }
        });

        btnTop.setBackground(new java.awt.Color(195, 195, 210));
        btnTop.setText("Top");
        btnTop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopActionPerformed(evt);
            }
        });

        lblTamMaximo.setText("Tamanho Maximo: ");

        lblTamAtual.setText("Numero de Elementos: ");

        pnlEstru.setBackground(new java.awt.Color(195, 195, 210));
        pnlEstru.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(220, 220, 230), new java.awt.Color(220, 220, 230), new java.awt.Color(160, 160, 190), new java.awt.Color(160, 160, 190)));
        pnlEstru.setLayout(new javax.swing.BoxLayout(pnlEstru, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pnlEstru);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPush)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPop))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(lblValor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTamAtual)
                                    .addComponent(lblTamMaximo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(btnTop))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(lblTamMaximo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTamAtual))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPop)
                    .addComponent(btnTop)
                    .addComponent(btnPush))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPushActionPerformed
        try {
            int valor = Integer.parseInt(txtValor.getText());
            pilha.push(valor);
            atualizar();
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Caracter inválido. Digite um número.");
        } catch (EstruturaCheiaException ex) {
            JOptionPane.showMessageDialog(null,ex.getMessage());
        }
    }//GEN-LAST:event_btnPushActionPerformed

    private void btnPopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPopActionPerformed
         try {
             int dado = pilha.pop();
             JOptionPane.showMessageDialog(null,"Dado removido com sucesso: " + dado);
             atualizar();
         }
         catch (EstruturaVaziaException e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
         }
    }//GEN-LAST:event_btnPopActionPerformed

    private void btnTopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTopActionPerformed
        try {
            int dado = pilha.top();
            JOptionPane.showMessageDialog(null, "O valor no topo é: " + dado);
        } catch (EstruturaVaziaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnTopActionPerformed

    private void atualizar() {
        lblTamAtual.setText("Numero de Elementos " + pilha.size());
        
        pnlEstru.removeAll();
        
        int[] array = pilha.getArray();
        
        for(int i = pilha.size() -1; i >= 0; i--) {
                JLabel lbl = new JLabel(new ImageIcon("Fotos//noduloSeq.png"));
                if(array[i] == 0) {
                    lbl.setIcon(new ImageIcon("Fotos//noduloNull.png"));
                }
                else{
                    lbl.setFont(new Font("Tahoma",Font.PLAIN,48));
                    lbl.setText("" + array[i] );
                    lbl.setHorizontalTextPosition(JLabel.CENTER);
                }
                
                pnlEstru.add(lbl);
        }

        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPop;
    private javax.swing.JButton btnPush;
    private javax.swing.JButton btnTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTamAtual;
    private javax.swing.JLabel lblTamMaximo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JPanel pnlEstru;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
