package Interface.Arvore;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

public class NoGrafico extends JPanel {

    private String value;
    
    private static ImageIcon normal = new ImageIcon("src//assets//NoArvore1.png");
    private static ImageIcon selected = new ImageIcon("src//assets//NoArvore2.png");;
    
    
    /** Creates new form Element
     * @param value */
    public NoGrafico(String value, boolean isSelected) {
        this.value = value;
        
        initComponents();
        
        if(isSelected) {
            elementLabel.setIcon(selected);
        }
        else {
            elementLabel.setIcon(normal);
        }
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        elementLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(165, 185, 250));
        setMaximumSize(new java.awt.Dimension(100, 100));
        setMinimumSize(new java.awt.Dimension(100, 100));
        setPreferredSize(new java.awt.Dimension(100, 100));

        elementLabel.setFont(new java.awt.Font("Tahoma", 1, 24));
        elementLabel.setHorizontalTextPosition(JLabel.CENTER);
        elementLabel.setText(value);
        elementLabel.setToolTipText(value);
        elementLabel.setMaximumSize(new java.awt.Dimension(100, 100));
        elementLabel.setMinimumSize(new java.awt.Dimension(100, 100));
        elementLabel.setOpaque(true);
        elementLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        elementLabel.setHorizontalAlignment(SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elementLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(elementLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setBorderColor(Color newColor){
        setBackground(newColor);
    }
    
    public JLabel getLabel(){
        return elementLabel;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel elementLabel;
    // End of variables declaration//GEN-END:variables

}
