package Interface.Arvore;

import Estruturas.ABP;
import Exceptions.*;
import javax.swing.JOptionPane;

public class pnlABP extends javax.swing.JPanel {

    private final ABP tree;

    public pnlABP() {
        initComponents();
        tree = new ABP(scrollPane);
        tree.showTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        actionPanel = new javax.swing.JPanel();
        valuePanel = new javax.swing.JPanel();
        lblValor = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        searchPanel = new javax.swing.JPanel();
        lblBusca = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setBackground(new java.awt.Color(195, 195, 210));

        actionPanel.setBackground(new java.awt.Color(195, 195, 210));
        actionPanel.setLayout(new java.awt.GridLayout(1, 0, 15, 0));

        valuePanel.setBackground(new java.awt.Color(195, 195, 210));
        valuePanel.setLayout(new javax.swing.BoxLayout(valuePanel, javax.swing.BoxLayout.LINE_AXIS));

        lblValor.setBackground(new java.awt.Color(195, 195, 210));
        lblValor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblValor.setText("Valor:");
        valuePanel.add(lblValor);

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });
        valuePanel.add(txtValor);

        btnAdicionar.setBackground(new java.awt.Color(195, 195, 210));
        btnAdicionar.setText("Adiconar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        valuePanel.add(btnAdicionar);

        actionPanel.add(valuePanel);

        searchPanel.setBackground(new java.awt.Color(195, 195, 210));
        searchPanel.setLayout(new javax.swing.BoxLayout(searchPanel, javax.swing.BoxLayout.LINE_AXIS));

        lblBusca.setBackground(new java.awt.Color(195, 195, 210));
        lblBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBusca.setText("Busca:");
        searchPanel.add(lblBusca);

        txtBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaActionPerformed(evt);
            }
        });
        searchPanel.add(txtBusca);

        btnBuscar.setBackground(new java.awt.Color(195, 195, 210));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        searchPanel.add(btnBuscar);

        actionPanel.add(searchPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane)
                    .addComponent(actionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        try {
            int value = Integer.parseInt(txtValor.getText());
            tree.insert(value);
            tree.showTree();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Caractere Invalido. Digite um numero");
        } catch (NumeroInvalidoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        try {
            int value = Integer.parseInt(txtBusca.getText());
            tree.search(value);
            tree.showTree(value);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Caractere Invalido. Digite um numero");
        } catch (DadoNaoEncontradoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        } catch (EstruturaVaziaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        btnAdicionar.doClick();
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        btnBuscar.doClick();
    }//GEN-LAST:event_txtBuscaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblValor;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtValor;
    private javax.swing.JPanel valuePanel;
    // End of variables declaration//GEN-END:variables
}
