
package Interface;

import Interface.Arvore.Espaco;
import Interface.Arvore.NoGrafico;
import Interface.Arvore.Seta;
import Interface.Arvore.pnlABP;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author aluno
 */
public class Main extends JFrame {
    /**
     * Creates new form NewJFrame
     */
    public Main() {
        initComponents();
        loadTreeAssets();
        setResizable(false);
        getContentPane().setBackground(new Color(195,195,210));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        buttonsPanel = new javax.swing.JPanel();
        btnListaSeq = new javax.swing.JButton();
        btnListaEnc = new javax.swing.JButton();
        btnPilha = new javax.swing.JButton();
        btnFila = new javax.swing.JButton();
        btnArvore = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(195, 195, 210));
        setForeground(new Color(195,195,210));
        setMaximumSize(new java.awt.Dimension(251, 275));
        setMinimumSize(new java.awt.Dimension(251, 275));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(134, 134, 164));
        titleLabel.setText("Estruturas:");
        titleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleLabelMouseClicked(evt);
            }
        });
        titleLabel.setHorizontalAlignment(SwingConstants.CENTER);

        buttonsPanel.setBackground(new java.awt.Color(195, 195, 210));
        buttonsPanel.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        btnListaSeq.setBackground(new java.awt.Color(195, 195, 210));
        btnListaSeq.setText("Lista Sequecial");
        btnListaSeq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaSeqActionPerformed(evt);
            }
        });
        buttonsPanel.add(btnListaSeq);

        btnListaEnc.setBackground(new java.awt.Color(195, 195, 210));
        btnListaEnc.setText("Lista Encadeada");
        btnListaEnc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaEncActionPerformed(evt);
            }
        });
        buttonsPanel.add(btnListaEnc);

        btnPilha.setBackground(new java.awt.Color(195, 195, 210));
        btnPilha.setText("Pilha");
        btnPilha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilhaActionPerformed(evt);
            }
        });
        buttonsPanel.add(btnPilha);

        btnFila.setBackground(new java.awt.Color(195, 195, 210));
        btnFila.setText("Fila");
        btnFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFilaActionPerformed(evt);
            }
        });
        buttonsPanel.add(btnFila);

        btnArvore.setBackground(new java.awt.Color(195, 195, 210));
        btnArvore.setText("Árvore");
        btnArvore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArvoreActionPerformed(evt);
            }
        });
        buttonsPanel.add(btnArvore);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buttonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(70, Short.MAX_VALUE)
                    .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListaSeqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaSeqActionPerformed
        try {
            String input = JOptionPane.showInputDialog("Informe o tamanho da estrutura: ");
            if( input == null ) return;
            int tam = Integer.parseInt(input);
            JFrame frame = new JFrame("Lista Sequencial");
            frame.add(new pnlListaSeq(tam));
            frame.setLocation(500, 250);
            frame.setSize(984, 350);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.setResizable(false);
            frame.setVisible(true);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Caracter invalido. Digite um numero.");
        }
    }//GEN-LAST:event_btnListaSeqActionPerformed

    private void btnListaEncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaEncActionPerformed
        JFrame frame = new JFrame("Lista Encadeada");
        frame.add(new pnlListaEnc());
        frame.setLocation(500, 250);
        frame.setSize(984, 350);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setResizable(false);
        frame.setVisible(true);
    }//GEN-LAST:event_btnListaEncActionPerformed

    private void btnPilhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilhaActionPerformed
        try {
             String input = JOptionPane.showInputDialog("Informe o tamanho da estrutura: ");
            if( input == null ) return;
            int tam = Integer.parseInt(input);
            JFrame frame = new JFrame("Pilha");
            frame.add(new pnlPilha(tam));
            frame.setLocation(500, 50);
            frame.setSize(300, 800);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.setResizable(false);
            frame.setVisible(true); 
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Caracter invalido. Digite um numero.");
        }
    }//GEN-LAST:event_btnPilhaActionPerformed

    private void btnFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFilaActionPerformed
       try {
            String input = JOptionPane.showInputDialog("Informe o tamanho da estrutura: ");
            if( input == null ) return;
            int tam = Integer.parseInt(input);
            JFrame frame = new JFrame("Fila");
            frame.add(new pnlFila(tam));
            frame.setLocation(500, 250);
            frame.setSize(984, 350);
            frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
            frame.setResizable(false);
            frame.setVisible(true);
       } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Caracter invalido. Digite um numero.");
        }
    }//GEN-LAST:event_btnFilaActionPerformed

    private void btnArvoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArvoreActionPerformed
        JFrame frame = new JFrame("Arvore Binaria");
        frame.add(new pnlABP());
        frame.setLocation(500, 250);
        frame.setSize(500, 500);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setResizable(true);
        frame.setVisible(true);
    }//GEN-LAST:event_btnArvoreActionPerformed

    private void titleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleLabelMouseClicked

    }//GEN-LAST:event_titleLabelMouseClicked

    private void loadTreeAssets(){
        
        new Espaco(1);
        setLocation(300, 200);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArvore;
    private javax.swing.JButton btnFila;
    private javax.swing.JButton btnListaEnc;
    private javax.swing.JButton btnListaSeq;
    private javax.swing.JButton btnPilha;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
