package Interface;

import Estruturas.ListaSeq;
import Exceptions.*;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author Pablo Suria
 */
public class pnlListaSeq extends javax.swing.JPanel {

    private final ListaSeq lista;
    private int pA;

    public pnlListaSeq(int tamanho) {
        initComponents();
        lista = new ListaSeq(tamanho, this);
        lblTamMaximo.setText(lblTamMaximo.getText() + tamanho);
        atualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblValor = new javax.swing.JLabel();
        btnAdicionar = new javax.swing.JButton();
        lblPosicao = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnRemover = new javax.swing.JButton();
        lblBusca = new javax.swing.JLabel();
        txtBusca = new javax.swing.JTextField();
        rBtnPosicao = new javax.swing.JRadioButton();
        rBtnValor = new javax.swing.JRadioButton();
        btnBuscar = new javax.swing.JButton();
        lblTamMaximo = new javax.swing.JLabel();
        lblTamAtual = new javax.swing.JLabel();
        txtPosicao = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();

        setBackground(new java.awt.Color(195, 195, 210));

        lblValor.setBackground(new java.awt.Color(134, 134, 164));
        lblValor.setText("Valor:");

        btnAdicionar.setBackground(new java.awt.Color(195, 195, 210));
        btnAdicionar.setText("Adiconar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        lblPosicao.setBackground(new java.awt.Color(134, 134, 164));
        lblPosicao.setText("Posiçao:");

        txtValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorActionPerformed(evt);
            }
        });

        btnRemover.setBackground(new java.awt.Color(195, 195, 210));
        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        lblBusca.setBackground(new java.awt.Color(134, 134, 164));
        lblBusca.setText("Busca:");

        rBtnPosicao.setBackground(new java.awt.Color(195, 195, 210));
        buttonGroup1.add(rBtnPosicao);
        rBtnPosicao.setText("Por Posição");

        rBtnValor.setBackground(new java.awt.Color(195, 195, 210));
        buttonGroup1.add(rBtnValor);
        rBtnValor.setText("Por Valor");

        btnBuscar.setBackground(new java.awt.Color(195, 195, 210));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblTamMaximo.setBackground(new java.awt.Color(134, 134, 164));
        lblTamMaximo.setText("Tamanho Maximo: ");

        lblTamAtual.setBackground(new java.awt.Color(134, 134, 164));
        lblTamAtual.setText("Numero de Elementos: ");

        txtPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPosicaoActionPerformed(evt);
            }
        });

        scrollPane.setBackground(new java.awt.Color(134, 134, 164));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPane)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPosicao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(114, 114, 114))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPosicao, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(lblValor, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                                    .addComponent(txtValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAdicionar, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnRemover, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBusca)
                                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rBtnValor)
                                    .addComponent(rBtnPosicao))
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTamAtual, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTamMaximo, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(20, 20, 20))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPosicao)
                            .addComponent(lblBusca)
                            .addComponent(rBtnPosicao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRemover)
                            .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPosicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rBtnValor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdicionar)
                            .addComponent(btnBuscar)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTamMaximo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblTamAtual)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        try {
            int pos = Integer.parseInt(txtPosicao.getText());
            int dado = lista.remove(pos);

            Elemento elem = new Elemento("" + dado, "src//assets//noduloSeq.png");
            JOptionPane.showMessageDialog(this, elem, "Info", JOptionPane.PLAIN_MESSAGE);

            pA = -1;
            atualizar();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Caracter invalido. Digite um numero!");
        } catch (NumeroInvalidoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        if (txtPosicao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite uma posicao.");
        } else if (txtValor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite um valor.");
        } else {
            try {
                int pos = Integer.parseInt(txtPosicao.getText());
                int valor = Integer.parseInt(txtValor.getText());

                pA = pos;
                atualizar();
                lista.insert(pos, valor);

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Caracter invalido. Digite um numero.");
            } catch (NumeroInvalidoException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            } catch (EstruturaCheiaException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (rBtnPosicao.isSelected()) {
            try {
                int bus = Integer.parseInt(txtBusca.getText());
                int dado = lista.searchPosition(bus);
                pA = bus;

                Elemento elem = new Elemento("" + dado, "src//assets//noduloSeq.png");
                JOptionPane.showMessageDialog(this, elem, "Valor na posicao:", JOptionPane.PLAIN_MESSAGE);

                atualizar();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Caracter invalido. Digite um numero.");
            } catch (NumeroInvalidoException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else if (rBtnValor.isSelected()) {
            try {
                int bus = Integer.parseInt(txtBusca.getText());
                int pos = lista.searchValue(bus);
                JOptionPane.showMessageDialog(null, "Valor encontrado na posicao: " + pos);
                pA = pos;
                atualizar();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Caracter invalido. Digite um numero.");
            } catch (DadoNaoEncontradoException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Escolha uma das opÃcoes de busca.");
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorActionPerformed
        btnAdicionar.doClick();
    }//GEN-LAST:event_txtValorActionPerformed

    private void txtPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPosicaoActionPerformed
        btnAdicionar.doClick();
    }//GEN-LAST:event_txtPosicaoActionPerformed

    public void atualizar() {
        Container cont = new Container();
        cont.setBackground(new Color(195,195,210));
        lblTamAtual.setText("Numero de Elementos " + lista.size());

        for (int i = 1; i <= lista.maxSize(); i++) {
            Elemento elem;
            try {
                if (i == pA) {
                    elem = new Elemento("" + lista.searchPosition(i), "src//assets//noduloSeq3.png");
                } else {
                    elem = new Elemento("" + lista.searchPosition(i), "src//assets//noduloSeq.png");
                }

                cont.add(elem);
            } catch (NumeroInvalidoException ex) {
                elem = new Elemento("", "src//assets//noduloNull.png");
                cont.add(elem);
            }
        }

        cont.setLayout(new BoxLayout(cont, BoxLayout.X_AXIS));
        int sValue = scrollPane.getHorizontalScrollBar().getValue();
        scrollPane.getViewport().setView(cont);
        scrollPane.getHorizontalScrollBar().setValue(sValue);
        scrollPane.getViewport().setBackground(new Color(195,195,210));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRemover;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblPosicao;
    private javax.swing.JLabel lblTamAtual;
    private javax.swing.JLabel lblTamMaximo;
    private javax.swing.JLabel lblValor;
    private javax.swing.JRadioButton rBtnPosicao;
    private javax.swing.JRadioButton rBtnValor;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtPosicao;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
